const AUTH_ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  EMAIL_MISSING: 'EMAIL_MISSING',
  USER_NOT_PROVISIONED: 'USER_NOT_PROVISIONED',
  USER_INACTIVE: 'USER_INACTIVE',
  INVALID_ROLE: 'INVALID_ROLE',
  ACCOUNT_LINK_CONFLICT: 'ACCOUNT_LINK_CONFLICT',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  CLERK_AUTH_REQUIRED: 'CLERK_AUTH_REQUIRED',
  REGISTRATION_DISABLED: 'REGISTRATION_DISABLED',
};

function authError(status, code, message) {
  return { status, code, message };
}

module.exports = {
  AUTH_ERROR_CODES,
  authError,
};
